### ISSUE TITLE
Deprecated selector in `ink\styles\ink.less`

### ISSUE THREAD

**Issue by GregPlowman** [JunoLab/atom-ink#112]
In `ink\styles\ink.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow div.block-notify .region` => `atom-text-editor.editor div.block-notify .region`

* `atom-text-editor::shadow div.block-notify.hidden .region` => `atom-text-editor.editor div.block-notify.syntax--hidden .region`

* `atom-text-editor::shadow div.doc-highlight .region` => `atom-text-editor.editor div.doc-highlight .region`

* `atom-text-editor::shadow div.ink.block` => `atom-text-editor.editor div.syntax--ink.syntax--block`

* `atom-text-editor::shadow div.ink.block.hidden` => `atom-text-editor.editor div.syntax--ink.syntax--block.syntax--hidden`

* `atom-text-editor::shadow .highlight.error-line .region` => `atom-text-editor.editor .highlight.error-line .region`

* `atom-text-editor::shadow .icon::before` => `atom-text-editor.editor .icon::before`

* `atom-text-editor::shadow .icon-diff-modified::before` => `atom-text-editor.editor .icon-diff-modified::before`

* `atom-text-editor::shadow .icon-chevron-right::before` => `atom-text-editor.editor .icon-chevron-right::before`

* `atom-text-editor::shadow .ink-bp` => `atom-text-editor.editor .ink-bp`

* `atom-text-editor::shadow .ink-bp.ink-hide` => `atom-text-editor.editor .ink-bp.ink-hide`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by joelrealubit** [comment]
**Prerequisites**
[x] Put an X between the brackets on this line if you have done all of the following:
o Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
o Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
o Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
o Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
o Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

**Description**
Under the Deprecation Cop pane for ink, the ff appears:

> ink\styles\ink.less
> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
> 
> atom-text-editor::shadow div.block-notify .region => atom-text-editor.editor div.block-notify .region
> atom-text-editor::shadow div.block-notify.hidden .region => atom-text-editor.editor div.block-notify.syntax--hidden .region
> atom-text-editor::shadow div.doc-highlight .region => atom-text-editor.editor div.doc-highlight .region
> atom-text-editor::shadow div.ink.block => atom-text-editor.editor div.syntax--ink.syntax--block
> atom-text-editor::shadow div.ink.block.hidden => atom-text-editor.editor div.syntax--ink.syntax--block.syntax--hidden
> atom-text-editor::shadow .highlight.error-line .region => atom-text-editor.editor .highlight.error-line .region
> atom-text-editor::shadow .icon::before => atom-text-editor.editor .icon::before
> atom-text-editor::shadow .icon-diff-modified::before => atom-text-editor.editor .icon-diff-modified::before
> atom-text-editor::shadow .icon-chevron-right::before => atom-text-editor.editor .icon-chevron-right::before
> atom-text-editor::shadow .ink-bp => atom-text-editor.editor .ink-bp
> atom-text-editor::shadow .ink-bp.ink-hide => atom-text-editor.editor .ink-bp.ink-hide
> Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Steps to Reproduce**
Start atom, bring up the Deprecation Tab pane, and you will find the aforementioned error.
Expected behavior: no deprecation alerts for ink
Actual behavior: that alert appears with the error message above.
Reproduces how often: 100%

**Versions**
Atom 1.13.0
Ink 0.6.2
Windows 10 Home
I set up atom the same way as described here: https://gist.github.com/jasongilman/d1f70507bed021b48625

**Additional Information**
n/a
