### ISSUE TITLE
Optimize css animations

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-ink#142]
ref https://github.com/JunoLab/atom-julia-client/issues/370.

**Comment by MikeInnes** [comment]
we could perhaps have a toggle to just avoid animations completely. Would need a good alternative for the progress bar though.

**Comment by pfitzseb** [comment]
I guess, but we could also put the css to disable animations into the docs...

**Comment by pfitzseb** [comment]
crossref: https://discourse.julialang.org/t/why-does-juno-make-my-code-run-slower-than-in-vscode/7846/

**Comment by ChrisRackauckas** [comment]
The alternative to the progress bar should come easily with the Base logging changes: when animations are turned off just punt the progress over to a console progress meter package like ProgressMeter.jl. Think this would be a nice toggle as long as it still has some (more static) way of saying that a computation is still in progress (instead of stuff spinning all of the time, just have an in progress image?)
