### ISSUE TITLE
deserialization of PaneItem broken

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-ink#71]
or rather not registered early enough. I get a warning whenever I restart Atom with some custom PaneItem open:

```
No deserializer found for Object {deserializer: "InkWorkspace", id: "julia"}
```

I suppose this is because Atom tries to deserialize the cached editor before loading the packages, since the deserializer we want appears in `atom.deserializers.deserializers` on package activation.

**Comment by MikeInnes** [comment]
This is happening because you broke Ink at some point :) Atom determines whether it can load a package before or after deserialisation; for some reason deferring gets set by package load failure and won't unset itself. But you can fix that by running:

``` js
p = atom.packages.getActivePackage('ink')
localStorage.setItem(p.getCanDeferMainModuleRequireStorageKey(), false)
```

from the console.

(This is the snippet that we ran on activation at one point, but removed since it seemed to cause issues with remembering window size.)

**Comment by pfitzseb** [comment]
Sweet, thanks (breaking ink happens quite often to me ;)).

Do you remember if we tried to defer running that command until after activation is complete or something like that? Or run it on deactivation?

**Comment by MikeInnes** [comment]
I think we only ever tried running it on activate – might be worth checking the history for that though. Waiting for Atom to finish activating or something might well give you more luck though.

**Comment by pfitzseb** [comment]
Just checked -- we didn't try anything else.

Clearing that setting on deactivation seems to work though. I'll push that change for now and we'll see if anything breaks again...
