### ISSUE TITLE
Custom keybindings not responding in REPL entry

### ISSUE THREAD

**Issue by jasongilman** [JunoLab/atom-ink#75]
This is a copy of an issue filed in Proto REPL [#161](https://github.com/jasongilman/proto-repl/issues/161). I think this is a problem with the Atom Ink Console.

> Hello. I updated today to 1.4.7 and have found some misbehavior with the text entry from the previous version I was using.
> 
> I use a Finnish keyboard, and a set of custom keybindings to rebind the ö, ä, and å keys to the braces. See here: https://gist.github.com/jarcane/468687e98176c1c4c8a7ba924dafdf46 (the use of `, \, and ] refers to the ö/ä/å keys, because Atom uses the American keymap only, internally)
> 
> Unfortunately, these keys don't work in the Proto-REPL pane, at all. It seems to simply ignore input from those keys entirely; I get no input.
> 
> I've also found that the automatic pairing of braces from Paredit isn't honored in the Proto-REPL window either, though that should perhaps be filed as a separate issue?

**Comment by pfitzseb** [comment]
Yeah, that's to be expected with how those commands are defined. `atom.workspace.getActiveTextEditor()` only works if the `TextEditor` is the active item in some Pane (see the implementation [here](https://github.com/atom/atom/blob/d3291f14127c7f2c58c052cc74e016adb5716cdf/src/workspace.coffee#L661)) -- imo this is somewhat unfortunate behaviour and should probably be fixed in Atom core. The paredit issue probably has the same cause, but not totally sure.

The best workaround for the keybinding stuff is probably to use the [keyboard-localization](https://atom.io/packages/keyboard-localization)-package, which works great for me even in the console.
